name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Backend/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: inventory-api
  REGION: asia-south1

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |
        cd Backend
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME --no-stream --async

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars "CORS_ORIGINS=https://nice-height-460409-m5.web.app" \
          --set-env-vars "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}"

    - name: Show Service URL
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
        echo "Backend deployed at: $SERVICE_URL"
